// Cues, muscle breakdowns and Mandarin names — sliced verbatim from the design canvas.

import { CANON } from './data';

export type Breakdown = [string, number][];

// short form cue per move — looked up by canonical name so swaps still get a cue
const HOWTO: Record<string, string> = {
  'Pull-up': 'Dead hang start, drive elbows down and back, chin clears the bar without swinging.',
  'Lat pulldown': 'Lean back slightly, pull the bar to your upper chest, lead with elbows not hands.',
  'Chin-up': 'Underhand grip, pull until chin clears the bar, control the descent to full extension.',
  'Neutral-grip pulldown': 'Palms facing each other, pull to chest, squeeze shoulder blades at the bottom.',
  'Single-arm pulldown': 'One handle at a time, brace your core, avoid rotating the torso as you pull.',
  'Assisted pull-up': 'Use the machine counterweight, keep the same pull-up form, slow the negative.',
  'Machine pull-up': 'Set the seat so arms start fully extended, drive elbows down to full contraction.',
  'Inverted row': 'Body straight under a bar, pull chest to the bar, squeeze shoulder blades together.',
  'Chest-supported row': 'Chest on the pad, pull elbows back past your ribs, no momentum from the legs.',
  'Seal row': 'Lying face down on the bench, row straight up, pause briefly at the top.',
  'Dumbbell row': 'Flat back, pull the elbow up along your side, avoid twisting the torso.',
  'T-bar row': 'Hip hinge, chest up, pull the handle into your stomach, squeeze at the top.',
  'Landmine row': 'One end of the bar anchored, row the free end to your hip, keep hips still.',
  'Smith machine row': 'Bar path fixed, hinge at the hips, pull to your lower ribs.',
  'Barbell row': 'Hip hinge to ~45°, pull the bar to your belly, keep the bar close to your shins.',
  'Seated cable row': 'Slight lean back at the top, drive elbows behind you, avoid using your back to yank.',
  'Chest-supported machine row': 'Chest against the pad the whole rep, pull handles to your ribs.',
  'Single-arm cable row': 'Anti-rotation — keep hips square while pulling one side.',
  'Wide-grip cable row': 'Wide grip, pull to your chest, elbows flare slightly out.',
  'Standing cable row': 'Stand facing the cable at chest height, pull the handle to your torso, squeeze the shoulder blades.',
  'Pulley': 'Seated row on the low pulley, drive elbows back, keep chest tall.',
  'Wide lat pull': 'Wide overhand grip on the pulldown, pull to the upper chest, elbows out and down.',
  'Close lat pull': 'Close underhand grip, pull to the chest, elbows stay close to the body.',
  'Lat pull': 'Lean back slightly, pull the bar to your upper chest, lead with elbows not hands.',
  '45 roman chair': 'Hips on the pad, hinge forward and back up to straight, keep the lower back neutral.',
  'Straight-arm pulldown': 'Arms stay straight, pull the bar down in an arc to your thighs.',
  'Cable pullover': 'Straight arms, pull from overhead down to your thighs, feel it in the lats.',
  'Machine pullover': 'Elbows on the pads, pull down and forward, stretch fully at the top.',
  'Dumbbell pullover': 'Lying on a bench, lower a dumbbell behind your head, pull it back over your chest.',
  'Band pulldown': 'Anchor the band overhead, pull down and back like a lat pulldown.',
  'Face pull': 'Rope at eye level, pull to your face, elbows high, squeeze the rear delts.',
  'Reverse fly': 'Slight bend forward, raise arms out to the sides, squeeze shoulder blades together.',
  'Reverse pec deck': 'Chest against the pad, arms wide, squeeze the rear delts at the back.',
  'Cable reverse fly': 'Cross-cable handles, pull arms out and back, keep a slight elbow bend.',
  'Bent-over dumbbell fly': 'Hinge at the hips, raise dumbbells out to the sides, lead with elbows.',
  'Rope upright row': 'Rope attachment, pull up along the body to chin height, elbows lead.',
  'Band pull-apart': 'Arms straight out front, pull the band apart to your chest, squeeze the back.',
  'Lateral raise': 'Slight bend in elbows, raise arms to shoulder height, lead with elbows not hands.',
  'Dumbbell lateral raise': 'Slight bend in elbows, raise to shoulder height, control the descent.',
  'Cable lateral raise': 'Cable behind you, raise the arm across the body up to shoulder height.',
  'Leaning cable raise': 'Lean away from the cable, raise the arm — the lean increases the stretch.',
  'Machine lateral raise': 'Set the seat so the pivot lines up with your shoulder, raise to horizontal.',
  'Band lateral raise': 'Stand on the band, raise arms to shoulder height against the resistance.',
  'Plate side raise': 'Hold a plate by the edges, raise it to shoulder height, control the lower.',
  'Front raise': 'Slight bend in elbows, raise the weight to shoulder height in front of you.',
  'Cable front raise': 'Cable between your legs or to the side, raise straight in front to shoulder height.',
  'Plate front raise': 'Hold a plate with both hands, raise straight up to eye level.',
  'Landmine raise': 'One end of the bar anchored, raise it in front of you like a front raise.',
  'Incline bench front raise': 'Lying face-down on an incline bench, raise dumbbells straight in front.',
  'Band front raise': 'Stand on the band, raise arms straight in front to shoulder height.',
  'Shoulder press': 'Press straight overhead, elbows track slightly forward, lock out without arching the back.',
  'Overhead press': 'Bar at collarbone, press straight overhead, brace your core to avoid arching.',
  'Machine shoulder press': 'Set the seat so handles start at shoulder height, press straight up.',
  'Seated dumbbell press': 'Seated with back support, press dumbbells overhead, avoid flaring elbows too wide.',
  'Smith machine press': 'Fixed bar path, press straight up from shoulder height, keep the core braced.',
  'Push press': 'Slight leg dip, drive up through the legs, then press the bar overhead.',
  'Cable shoulder press': 'Cable from a low anchor, press straight overhead, keep the core tight.',
  'Landmine press': 'One end of the bar anchored at your shoulder, press it up and forward.',
  'Pike push-up': "Hips high in a pike position, lower your head toward the floor, press back up.",
  'Arnold press': 'Start palms facing you, rotate to face forward as you press overhead.',
  'Standing dumbbell press': 'Standing, brace the core hard, press dumbbells overhead without leaning back.',
  'Chest press': 'Set the seat so handles line up with mid-chest, press straight out.',
  'Dumbell Bench press': 'Dumbbells at chest height, press straight up, bring them slightly together at the top.',
  'Bench press': 'Bar to mid-chest, elbows at about 45°, press up in a slight arc.',
  'Dumbbell bench press': 'Dumbbells at chest height, press up, control the descent to a full stretch.',
  'Machine chest press': 'Handles start at chest height, press straight forward, avoid locking elbows hard.',
  'Smith machine bench': 'Fixed bar path, lower to chest, press up along the same line.',
  'Floor press': 'Lying on the floor, lower until your elbows touch the ground, press back up.',
  'Cable chest press': 'Cables at chest height, press forward and slightly together, squeeze at the end.',
  'Weighted push-up': 'Added weight on your back, full range chest-to-floor push-up, body stays rigid.',
  'Incline bench press': 'Bench at 30–45°, bar to upper chest, press up and slightly back.',
  'Incline dumbbell press': 'Incline bench, dumbbells to upper chest, press up in a slight arc.',
  'Incline machine press': 'Set the seat for an incline press angle, press straight out.',
  'Incline cable press': 'Low cable, press up and forward at an incline angle.',
  'Incline barbell press': 'Incline bench, bar to upper chest, press straight up.',
  'Low-to-high cable fly': 'Cables set low, sweep up and across to target the upper chest.',
  'High-to-low cable fly': 'Cables set high, sweep down and across toward your hips to target the lower chest.',
  'Incline push-up': 'Hands on a bench or box, lower your chest to the edge, press back up.',
  'Pec fly': 'Arms slightly bent, bring them together in front of your chest, control the stretch back.',
  'Cable fly': 'Cables at shoulder height, bring hands together in front of your chest.',
  'Cross-body cable fly': 'One cable, pull across your body to the opposite hip, squeeze the chest.',
  'Pec deck': 'Elbows on the pads, bring them together in front of your chest.',
  'Dumbbell fly': 'Lying on a bench, lower dumbbells out to the sides, bring them back together over your chest.',
  'Incline dumbbell fly': 'Incline bench, lower dumbbells out to the sides, bring them back over your upper chest.',
  'Band fly': 'Anchor a band behind you, bring hands together in front of your chest.',
  'Chest dip': 'Lean forward on the dip bars, lower until shoulders are below elbows, press back up.',
  'Weighted dip': 'Added weight on a belt, same lean-forward dip form, control the descent.',
  'Decline bench press': 'Decline bench, bar to lower chest, press straight up.',
  'Dip machine': 'Set the counterweight, same lean-forward dip motion, control the lowering.',
  'Bodyweight dip': 'Lean forward on the bars, lower with control, press back to full extension.',
  'Decline push-up': 'Feet elevated on a bench, lower your chest to the floor, press back up.',
  'Push-up to failure': "Standard push-up form, keep going until you can't complete a full rep.",
  'Dumbbell floor press': 'Lying on the floor, lower dumbbells until your elbows touch down, press up.',
  'Deficit push-up': 'Hands on blocks or plates, lower your chest below hand height, press back up.',
  'Band push-up': 'Band across your back, standard push-up form against the extra resistance.',
  'Abductor': 'Seated, push your knees outward against the pads, control the return.',
  'Adductor': 'Seated, squeeze your knees together against the pads, control the return.',
  'Calves raises': 'Rise onto your toes as high as possible, pause, lower with control past level.',
  'Standing calf raise': 'Rise onto your toes, pause at the top, lower slowly below the platform.',
  'Dumbbell single-leg calf raise': 'Dumbbell in one hand, ball of the other foot on a step, rise high, lower below the step.',
  'Hack squat single-leg calf raise': 'One foot on the low edge of the hack squat plate, shoulders under the pads, full stretch then rise.',
  'Seated calf raise': 'Seated with pads on your knees, rise onto your toes, full stretch at the bottom.',
  'Smith machine calf raise': 'Fixed bar path on your shoulders, rise onto your toes, full range each rep.',
  'Donkey calf raise': 'Bent forward at the hips, rise onto your toes, get a deep stretch at the bottom.',
  'Leg press calf raise': 'Feet on the bottom edge of the platform, press through your toes, full range.',
  'Dumbell squat': 'Dumbbells at your sides or on shoulders, squat to at least parallel, knees track over toes.',
  'Front squat': 'Bar on front delts, elbows high, squat keeping your torso upright.',
  'Back squat': 'Bar on your upper back, sit back and down, drive up through your heels.',
  'Hack squat': 'Shoulders and back against the pads, squat down, drive through your whole foot.',
  'Smith machine squat': 'Fixed bar path, squat to at least parallel, keep your chest up.',
  'Belt squat': 'Weight hangs from a belt at your hips, squat with no spinal load.',
  'Leg press': 'Feet shoulder-width on the platform, lower until knees are near 90°, press through your heels.',
  'Goblet squat': 'Hold a dumbbell at your chest, squat between your knees, keep elbows inside your knees.',
  'Leg extension': 'Pad against your shins, extend your knees fully, pause, lower with control.',
  'Pistol Squat': 'Single-leg squat, other leg extended forward, sit back and down keeping your heel planted.',
  'Pistol squat': 'Single-leg squat, other leg extended forward, sit back and down keeping your heel planted.',
  'Bulgarian split squat': 'Rear foot elevated behind you, lower the front knee, drive up through the front heel.',
  'Box pistol squat': 'Single-leg squat down to a box for depth control, stand back up.',
  'Assisted pistol squat': 'Hold a support for balance, single-leg squat down and back up.',
  'Walking lunge': 'Step forward, lower the rear knee toward the floor, push off into the next step.',
  'Step-up': 'Step fully onto a box with one foot, drive up without pushing off the trailing leg.',
  'Leg curl': 'Curl your heels toward your glutes, pause, lower with control against the pad.',
  'Seated leg curl': 'Pad against your shins, curl your heels down and under the seat.',
  'Lying leg curl': 'Face down, curl your heels toward your glutes, control the lowering.',
  'Romanian deadlift': 'Soft knees, push hips back, bar close to your legs, feel the stretch in your hamstrings.',
  'Single-leg RDL': 'One leg planted, hinge forward as the other leg lifts back, keep hips square.',
  'Good morning': 'Bar on your back, hinge at the hips with a slight knee bend, keep your back flat.',
  'Cable pull-through': 'Cable between your legs, hinge at the hips, drive through with your glutes to stand.',
  'Hip thrust': 'Upper back on a bench, drive hips up by squeezing your glutes, pause at the top.',
  'Triceps': 'Isolate the triceps with full extension at the top, control the negative.',
  'Tricep': 'Isolate the triceps with full extension at the top, control the negative.',
  'Tricep dip': 'Hands behind you on a bench, lower with elbows back, press up through the triceps.',
  'Bench dip': 'Hands on a bench behind you, feet out front, lower and press back up.',
  'Tricep rope pushdown': 'Elbows pinned at your sides, push the rope down and slightly apart at the bottom.',
  'Rope pushdown': 'Elbows pinned at your sides, push the rope down, spread it apart at the bottom.',
  'Overhead cable extension': 'Cable behind your head, extend your arms overhead, keep elbows pointed forward.',
  'Overhead rope extension': 'Rope overhead, extend your arms, keep elbows fixed and pointed forward.',
  'Skull crusher': 'Lying down, lower the bar toward your forehead, keep your upper arms vertical.',
  'Single-arm cable extension': 'One arm at a time, elbow pinned at your side, extend fully.',
  'Bar pushdown': 'Elbows pinned at your sides, push the bar down to full extension.',
  'Close-grip bench press': 'Hands shoulder-width or closer, elbows tucked, press with a triceps focus.',
  'Dumbbell kickback': 'Hinge forward, upper arm parallel to the floor, extend the forearm back.',
  'Biceps': 'Curl with control, squeeze at the top, avoid swinging your elbows forward.',
  'Barbell curl': 'Elbows pinned at your sides, curl the bar up, avoid leaning back to cheat it up.',
  'Hammer curl': 'Neutral grip, curl straight up, keep your elbows pinned at your sides.',
  'Cable curl': 'Cable at the bottom, elbows pinned, curl up with constant tension.',
  'Preacher curl': 'Arm braced on the pad, curl up without letting the elbow lift off.',
  'EZ-bar curl': 'Angled grip on the bar, curl up keeping elbows fixed at your sides.',
  'Dumbbell curl': 'Curl one or both dumbbells, rotate to palm-up as you lift, control the descent.',
  'Machine curl': 'Set the seat so your elbow lines up with the pivot, curl fully.',
  'Incline dumbbell curl': 'Lying back on an incline bench, curl with a deep stretch at the bottom.',
  'Cable hammer curl': 'Rope attachment, neutral grip, curl straight up keeping elbows pinned.',
  'Rope hammer curl': 'Rope attachment, neutral grip, curl up, squeeze at the top.',
  'Zottman curl': 'Curl up palm-up, rotate to palm-down, lower slowly for the eccentric.',
  'Reverse curl': 'Overhand grip, curl up focusing on the forearms and biceps.',
  'Hanging leg raise': 'Hang from the bar, raise your legs to hip height or higher without swinging.',
  'Cable crunch': 'Kneeling, crunch down bringing your elbows toward your knees, round your spine.',
  'Ab wheel': 'Roll out slowly keeping your core braced, pull back in before your hips sag.',
  'Decline sit-up': 'Feet anchored on a decline bench, sit up with control, avoid yanking your neck.',
  'Plank': 'Straight line from head to heels, brace your core, breathe steadily.',
  'Handstand hold': 'Hands shoulder-width, stack shoulders over wrists, brace your core and hold as long as you can.',
  'Frogstand hold': 'Hands on the floor, knees resting on your triceps, lean forward until your feet lift, hold your balance.',
};

const HOWTO_FALLBACK: Record<string, string> = {
  SHOULDER: 'Controlled range, lead with elbows, avoid using momentum.',
  BACK: 'Pull with your back, not your arms — squeeze at the end range.',
  CHEST: 'Control the stretch, press with control, avoid locking out hard.',
  LEGS: 'Keep your knees tracking over your toes, control the descent.',
  BICEP: 'Keep elbows pinned, curl through a full range, control the negative.',
  TRICEP: 'Keep elbows fixed, extend fully, control the negative.',
  CORE: 'Controlled range, brace before each rep.',
  BALANCE: 'Hold with control, breathe steadily.',
};

export const cueFor = (name: string, g: string): string =>
  HOWTO[CANON(name)] || HOWTO[name] || HOWTO_FALLBACK[g] || '';

// approximate muscle-emphasis breakdown by movement keyword — general anatomy/EMG-informed
// estimates for orientation, not a single-study citation
function muscleBreakdown(name: string): Breakdown | null {
  const n = name.toLowerCase();
  if (/face pull|reverse (fly|pec)|rear delt|rope upright|pull-apart/.test(n)) return [['Rear Delts', 55], ['Traps', 25], ['Rhomboids', 20]];
  if (/pullover|straight-arm/.test(n)) return [['Lats', 70], ['Triceps', 18], ['Chest', 12]];
  if (/deadlift|good morning|pull-through|rdl/.test(n)) return [['Hamstrings', 48], ['Glutes', 34], ['Erectors', 18]];
  if (/tricep dip|bench dip|close-grip/.test(n)) return [['Triceps', 78], ['Front Delts', 12], ['Chest', 10]];
  if (/row|pulldown|pull-up|pull up|chin-up|inverted row/.test(n)) return [['Lats', 52], ['Biceps', 22], ['Rear Delts', 16], ['Traps', 10]];
  if (/lateral raise|side raise/.test(n)) return [['Side Delts', 82], ['Front Delts', 10], ['Traps', 8]];
  if (/front raise/.test(n)) return [['Front Delts', 80], ['Side Delts', 14], ['Chest', 6]];
  if (/arnold|overhead press|shoulder press|push press|pike push|landmine press/.test(n)) return [['Front Delts', 48], ['Side Delts', 30], ['Triceps', 22]];
  if (/fly|pec deck/.test(n)) return [['Chest', 78], ['Front Delts', 22]];
  if (/bench press|chest press|floor press|push-up|dip/.test(n)) return [['Chest', 58], ['Triceps', 26], ['Front Delts', 16]];
  if (/leg extension/.test(n)) return [['Quads', 92], ['Hip Flexors', 8]];
  if (/leg curl/.test(n)) return [['Hamstrings', 85], ['Calves', 15]];
  if (/squat|leg press|lunge|step-up|hack|bulgarian|pistol/.test(n)) return [['Quads', 55], ['Glutes', 30], ['Hamstrings', 15]];
  if (/hip thrust/.test(n)) return [['Glutes', 68], ['Hamstrings', 32]];
  if (/calf|calves/.test(n)) return [['Calves', 95], ['Soleus', 5]];
  if (/abductor/.test(n)) return [['Glute Medius', 90], ['Outer Thigh', 10]];
  if (/adductor/.test(n)) return [['Adductors', 95], ['Inner Thigh', 5]];
  if (/curl/.test(n)) return [['Biceps', 82], ['Forearms', 18]];
  if (/pushdown|skull crusher|kickback|extension/.test(n)) return [['Triceps', 88], ['Front Delts', 12]];
  if (/crunch|sit-up|leg raise|ab wheel|plank|dragon flag/.test(n)) return [['Rectus Abdominis', 65], ['Hip Flexors', 25], ['Obliques', 10]];
  if (/handstand|frogstand/.test(n)) return [['Front Delts', 40], ['Core', 35], ['Forearms', 25]];
  if (/roman chair/.test(n)) return [['Erectors', 70], ['Glutes', 20], ['Hamstrings', 10]];
  return null;
}

const BREAKDOWN_FALLBACK: Record<string, Breakdown> = {
  SHOULDER: [['Side Delts', 50], ['Front Delts', 30], ['Traps', 20]],
  BACK: [['Lats', 55], ['Rhomboids', 25], ['Rear Delts', 20]],
  CHEST: [['Chest', 75], ['Front Delts', 25]],
  LEGS: [['Quads', 50], ['Glutes', 30], ['Hamstrings', 20]],
  BICEP: [['Biceps', 85], ['Forearms', 15]],
  TRICEP: [['Triceps', 90], ['Front Delts', 10]],
  CORE: [['Rectus Abdominis', 70], ['Obliques', 30]],
  BALANCE: [['Front Delts', 40], ['Core', 35], ['Forearms', 25]],
};

export const breakdownFor = (name: string, g: string): Breakdown =>
  muscleBreakdown(name) || BREAKDOWN_FALLBACK[g] || [[g, 100]];

export const MANDARIN: Record<string, [string, string]> = {
  'Pull-up': ['引体向上', 'Yǐntǐ xiàngshàng'], 'Pull up': ['引体向上', 'Yǐntǐ xiàngshàng'],
  'Lat pulldown': ['高位下拉', 'Gāowèi xiàlā'], 'Chin-up': ['反握引体向上', 'Fǎnwò yǐntǐ xiàngshàng'],
  'Neutral-grip pulldown': ['对握下拉', 'Duìwò xiàlā'], 'Single-arm pulldown': ['单臂下拉', 'Dānbì xiàlā'],
  'Assisted pull-up': ['辅助引体向上', 'Fǔzhù yǐntǐ xiàngshàng'], 'Machine pull-up': ['器械引体向上', 'Qìxiè yǐntǐ xiàngshàng'],
  'Inverted row': ['反向划船', 'Fǎnxiàng huáchuán'], 'Chest-supported row': ['俯身支撑划船', 'Fǔshēn zhīchēng huáchuán'],
  'Seal row': ['海豹划船', 'Hǎibào huáchuán'], 'Dumbbell row': ['哑铃划船', 'Yǎlíng huáchuán'],
  'T-bar row': ['T杠划船', 'T gàng huáchuán'], 'Landmine row': ['地雷管划船', 'Dìléiguǎn huáchuán'],
  'Smith machine row': ['史密斯划船', 'Shǐmìsī huáchuán'], 'Barbell row': ['杠铃划船', 'Gànglíng huáchuán'],
  'Seated cable row': ['坐姿绳索划船', 'Zuòzī shéngsuǒ huáchuán'], 'Chest-supported machine row': ['器械俯身划船', 'Qìxiè fǔshēn huáchuán'],
  'Single-arm cable row': ['单臂绳索划船', 'Dānbì shéngsuǒ huáchuán'], 'Wide-grip cable row': ['宽握绳索划船', 'Kuānwò shéngsuǒ huáchuán'],
  'Standing cable row': ['站姿绳索划船', 'Zhànzī shéngsuǒ huáchuán'], 'Pulley': ['坐姿滑轮划船', 'Zuòzī huálún huáchuán'],
  'Wide lat pull': ['宽握下拉', 'Kuānwò xiàlā'], 'Close lat pull': ['窄握下拉', 'Zhǎiwò xiàlā'],
  'Lat pull': ['下拉', 'Xiàlā'], '45 roman chair': ['45度罗马椅', 'Sìshíwǔ dù luómǎ yǐ'],
  'Straight-arm pulldown': ['直臂下拉', 'Zhíbì xiàlā'], 'Cable pullover': ['绳索直臂下拉', 'Shéngsuǒ zhíbì xiàlā'],
  'Machine pullover': ['器械挺身', 'Qìxiè tǐngshēn'], 'Dumbbell pullover': ['哑铃挺身', 'Yǎlíng tǐngshēn'],
  'Band pulldown': ['弹力带下拉', 'Tánlìdài xiàlā'], 'Face pull': ['面拉', 'Miàn lā'],
  'Reverse fly': ['反向飞鸟', 'Fǎnxiàng fēiniǎo'], 'Rear delt fly': ['后束飞鸟', 'Hòushù fēiniǎo'],
  'Reverse pec deck': ['反向蝴蝶机', 'Fǎnxiàng húdié jī'], 'Cable reverse fly': ['绳索反向飞鸟', 'Shéngsuǒ fǎnxiàng fēiniǎo'],
  'Bent-over dumbbell fly': ['俯身哑铃飞鸟', 'Fǔshēn yǎlíng fēiniǎo'], 'Rope upright row': ['绳索直立划船', 'Shéngsuǒ zhílì huáchuán'],
  'Band pull-apart': ['弹力带拉花', 'Tánlìdài lā huā'], 'Lateral raise': ['侧平举', 'Cè píngjǔ'],
  'Dumbbell lateral raise': ['哑铃侧平举', 'Yǎlíng cè píngjǔ'], 'Cable lateral raise': ['绳索侧平举', 'Shéngsuǒ cè píngjǔ'],
  'Leaning cable raise': ['侧倾绳索侧平举', 'Cèqīng shéngsuǒ cè píngjǔ'], 'Machine lateral raise': ['器械侧平举', 'Qìxiè cè píngjǔ'],
  'Band lateral raise': ['弹力带侧平举', 'Tánlìdài cè píngjǔ'], 'Plate side raise': ['杠铃片侧平举', 'Gànglíngpiàn cè píngjǔ'],
  'Front raise': ['前平举', 'Qián píngjǔ'], 'Cable front raise': ['绳索前平举', 'Shéngsuǒ qián píngjǔ'],
  'Plate front raise': ['杠铃片前平举', 'Gànglíngpiàn qián píngjǔ'], 'Landmine raise': ['地雷管前举', 'Dìléiguǎn qián jǔ'],
  'Incline bench front raise': ['俯卧上斜前平举', "Fǔwò shàngxié qián píngjǔ"], 'Band front raise': ['弹力带前平举', 'Tánlìdài qián píngjǔ'],
  'Shoulder press': ['肩推', 'Jiān tuī'], 'Overhead press': ['站姿推举', 'Zhàn zī tuījǔ'],
  'Machine shoulder press': ['器械肩推', 'Qìxiè jiān tuī'], 'Seated dumbbell press': ['坐姿哑铃推举', 'Zuòzī yǎlíng tuījǔ'],
  'Smith machine press': ['史密斯推举', 'Shǐmìsī tuījǔ'], 'Push press': ['借力推举', 'Jièlì tuījǔ'],
  'Cable shoulder press': ['绳索肩推', 'Shéngsuǒ jiān tuī'], 'Landmine press': ['地雷管推举', 'Dìléiguǎn tuījǔ'],
  'Pike push-up': ['顶峰俯卧撑', 'Dǐngfēng fǔwòchēng'], 'Arnold press': ['阿诺德推举', 'Ānuòdé tuījǔ'],
  'Standing dumbbell press': ['站姿哑铃推举', 'Zhànzī yǎlíng tuījǔ'], 'Chest press': ['坐姿推胸', 'Zuòzī tuī xiōng'],
  'Dumbell Bench press': ['哑铃卧推', 'Yǎlíng wòtuī'], 'Bench press': ['卧推', 'Wòtuī'],
  'Dumbbell bench press': ['哑铃卧推', 'Yǎlíng wòtuī'], 'Machine chest press': ['器械推胸', 'Qìxiè tuī xiōng'],
  'Smith machine bench': ['史密斯卧推', 'Shǐmìsī wòtuī'], 'Floor press': ['地板卧推', 'Dìbǎn wòtuī'],
  'Cable chest press': ['绳索推胸', 'Shéngsuǒ tuī xiōng'], 'Weighted push-up': ['负重俯卧撑', 'Fùzhòng fǔwòchēng'],
  'Incline bench press': ['上斜卧推', 'Shàngxié wòtuī'], 'Incline dumbbell press': ['上斜哑铃卧推', 'Shàngxié yǎlíng wòtuī'],
  'Incline machine press': ['上斜器械推胸', 'Shàngxié qìxiè tuī xiōng'], 'Incline cable press': ['上斜绳索推胸', 'Shàngxié shéngsuǒ tuī xiōng'],
  'Incline barbell press': ['上斜杠铃卧推', 'Shàngxié gànglíng wòtuī'], 'Low-to-high cable fly': ['下上夹胸', 'Xià shàng jiā xiōng'], 'High-to-low cable fly': ['上下夹胸', 'Shàng xià jiā xiōng'],
  'Incline push-up': ['上斜俯卧撑', 'Shàngxié fǔwòchēng'], 'Pec fly': ['夹胸', 'Jiā xiōng'],
  'Cable fly': ['绳索夹胸', 'Shéngsuǒ jiā xiōng'], 'Cross-body cable fly': ['交叉绳索夹胸', 'Jiāochā shéngsuǒ jiā xiōng'],
  'Pec deck': ['蝴蝶机夹胸', 'Húdié jī jiā xiōng'], 'Dumbbell fly': ['哑铃飞鸟', 'Yǎlíng fēiniǎo'],
  'Incline dumbbell fly': ['上斜哑铃飞鸟', 'Shàngxié yǎlíng fēiniǎo'], 'Band fly': ['弹力带夹胸', 'Tánlìdài jiā xiōng'],
  'Chest dip': ['双杠臂屈伸', 'Shuānggàng bìqūshēn'], 'Weighted dip': ['负重双杠臂屈伸', 'Fùzhòng shuānggàng bìqūshēn'],
  'Decline bench press': ['下斜卧推', 'Xiàxié wòtuī'], 'Dip machine': ['双杠臂屈伸机', 'Shuānggàng bìqūshēn jī'],
  'Bodyweight dip': ['自重臂屈伸', 'Zìzhòng bìqūshēn'], 'Decline push-up': ['下斜俯卧撑', 'Xiàxié fǔwòchēng'],
  'Push-up to failure': ['力竭俯卧撑', 'Lìjié fǔwòchēng'], 'Dumbbell floor press': ['哑铃地板卧推', 'Yǎlíng dìbǎn wòtuī'],
  'Deficit push-up': ['缺口俯卧撑', 'Quēkǒu fǔwòchēng'], 'Band push-up': ['弹力带俯卧撑', 'Tánlìdài fǔwòchēng'],
  'Abductor': ['髋外展', 'Kuān wàizhǎn'], 'Adductor': ['髋内收', 'Kuān nèishōu'],
  'Calves raises': ['提踵', 'Tízhǒng'], 'Standing calf raise': ['站姿提踵', 'Zhànzī tízhǒng'],
  'Dumbbell single-leg calf raise': ['哑铃单腿提踵', 'Yǎlíng dāntuǐ tízhǒng'],
  'Hack squat single-leg calf raise': ['哈克机单腿提踵', 'Hākè jī dāntuǐ tízhǒng'], 'Seated calf raise': ['坐姿提踵', 'Zuòzī tízhǒng'],
  'Smith machine calf raise': ['史密斯提踵', 'Shǐmìsī tízhǒng'], 'Donkey calf raise': ['驴式提踵', 'Lǘ shì tízhǒng'],
  'Leg press calf raise': ['腿举机提踵', 'Tuǐjǔ jī tízhǒng'], 'Dumbell squat': ['哑铃深蹲', 'Yǎlíng shēndūn'],
  'Front squat': ['前蹲', 'Qián dūn'], 'Back squat': ['杠铃深蹲', 'Gànglíng shēndūn'],
  'Hack squat': ['哈克深蹲', 'Hākè shēndūn'], 'Smith machine squat': ['史密斯深蹲', 'Shǐmìsī shēndūn'],
  'Belt squat': ['腰带深蹲', 'Yāodài shēndūn'], 'Leg press': ['腿举', 'Tuǐ jǔ'],
  'Goblet squat': ['高脚杯深蹲', 'Gāojiǎobēi shēndūn'], 'Leg extension': ['腿屈伸', 'Tuǐ qūshēn'],
  'Pistol Squat': ['单腿深蹲', 'Dāntuǐ shēndūn'], 'Pistol squat': ['单腿深蹲', 'Dāntuǐ shēndūn'],
  'Bulgarian split squat': ['保加利亚分腿蹲', 'Bǎojiālìyǎ fēntuǐ dūn'], 'Box pistol squat': ['箱式单腿深蹲', 'Xiāng shì dāntuǐ shēndūn'],
  'Assisted pistol squat': ['辅助单腿深蹲', 'Fǔzhù dāntuǐ shēndūn'], 'Walking lunge': ['行走弓步', 'Xíngzǒu gōngbù'],
  'Step-up': ['上箱蹬', 'Shàng xiāng dēng'], 'Leg curl': ['腿弯举', 'Tuǐ wānjǔ'],
  'Seated leg curl': ['坐姿腿弯举', 'Zuòzī tuǐ wānjǔ'], 'Lying leg curl': ['俯卧腿弯举', 'Fǔwò tuǐ wānjǔ'],
  'Romanian deadlift': ['罗马尼亚硬拉', 'Luómǎníyà yìnglā'], 'Single-leg RDL': ['单腿罗马尼亚硬拉', 'Dāntuǐ luómǎníyà yìnglā'],
  'Good morning': ['早安式', "Zǎo'ān shì"], 'Cable pull-through': ['绳索硬拉', 'Shéngsuǒ yìnglā'],
  'Hip thrust': ['臀桥', 'Tún qiáo'], 'Triceps': ['三头肌训练', 'Sāntóujī xùnliàn'],
  'Tricep': ['三头肌训练', 'Sāntóujī xùnliàn'], 'Tricep dip': ['三头肌臂屈伸', 'Sāntóujī bìqūshēn'],
  'Bench dip': ['长凳臂屈伸', 'Chángdèng bìqūshēn'], 'Tricep rope pushdown': ['绳索下压', 'Shéngsuǒ xiàyā'],
  'Rope pushdown': ['绳索下压', 'Shéngsuǒ xiàyā'], 'Overhead cable extension': ['绳索头后臂屈伸', 'Shéngsuǒ tóuhòu bìqūshēn'],
  'Overhead rope extension': ['绳索头后臂屈伸', 'Shéngsuǒ tóuhòu bìqūshēn'], 'Skull crusher': ['卧姿臂屈伸', 'Wòzī bìqūshēn'],
  'Single-arm cable extension': ['单臂绳索臂屈伸', 'Dānbì shéngsuǒ bìqūshēn'], 'Bar pushdown': ['直杆下压', 'Zhígǎn xiàyā'],
  'Close-grip bench press': ['窄握卧推', 'Zhǎiwò wòtuī'], 'Dumbbell kickback': ['哑铃臂屈伸后踢', 'Yǎlíng bìqūshēn hòutī'],
  'Biceps': ['二头肌训练', 'Èrtóujī xùnliàn'], 'Barbell curl': ['杠铃弯举', 'Gànglíng wānjǔ'],
  'Hammer curl': ['锤式弯举', 'Chuí shì wānjǔ'], 'Cable curl': ['绳索弯举', 'Shéngsuǒ wānjǔ'],
  'Preacher curl': ['牧师凳弯举', 'Mùshī dèng wānjǔ'], 'EZ-bar curl': ['曲杆弯举', 'Qūgǎn wānjǔ'],
  'Dumbbell curl': ['哑铃弯举', 'Yǎlíng wānjǔ'], 'Machine curl': ['器械弯举', 'Qìxiè wānjǔ'],
  'Incline dumbbell curl': ['上斜哑铃弯举', 'Shàngxié yǎlíng wānjǔ'], 'Cable hammer curl': ['绳索锤式弯举', 'Shéngsuǒ chuí shì wānjǔ'],
  'Rope hammer curl': ['绳索锤式弯举', 'Shéngsuǒ chuí shì wānjǔ'], 'Zottman curl': ['佐特曼弯举', 'Zuǒtèmàn wānjǔ'],
  'Reverse curl': ['反握弯举', 'Fǎnwò wānjǔ'],
  'Hanging leg raise': ['悬垂举腿', 'Xuánchuí jǔ tuǐ'], 'Cable crunch': ['绳索卷腹', 'Shéngsuǒ juǎnfù'],
  'Ab wheel': ['健腹轮', 'Jiàn fù lún'], 'Decline sit-up': ['下斜仰卧起坐', 'Xiàxié yǎngwò qǐzuò'],
  'Plank': ['平板支撑', 'Píngbǎn zhīchēng'], 'Handstand hold': ['手倒立', 'Shǒu dàolì'],
  'Frogstand hold': ['青蛙倒立', 'Qīngwā dàolì'], 'Dragon flag': ['龙旗', 'Lóng qí'],
  'Frog Stand': ['青蛙倒立', 'Qīngwā dàolì'], 'Advanced Frog Stand': ['进阶青蛙倒立', 'Jìnjiē qīngwā dàolì'],
  'Tuck Swings': ['团身摆动', 'Tuánshēn bǎidòng'], 'Tuck Planche': ['团身俄挺', 'Tuánshēn é tǐng'],
  'Advanced Tuck Planche': ['进阶团身俄挺', 'Jìnjiē tuánshēn é tǐng'], 'Tuck Planche Push Ups': ['团身俄挺俯卧撑', 'Tuánshēn é tǐng fǔwòchēng'],
  'One Leg Planche': ['单腿俄挺', 'Dān tuǐ é tǐng'], 'Straddle Planche': ['分腿俄挺', 'Fēn tuǐ é tǐng'],
  'Full Planche': ['完全俄挺', 'Wánquán é tǐng'],
  'Wall Plank': ['靠墙平板支撑', 'Kào qiáng píngbǎn zhīchēng'], 'Wall Handstand Hold': ['靠墙倒立', 'Kào qiáng dàolì'],
  'Wall Heel Taps': ['靠墙倒立点脚跟', 'Kào qiáng dàolì diǎn jiǎogēn'], 'Wall Freestanding Hold': ['离墙倒立', 'Lí qiáng dàolì'],
  'Freestanding Hold (with spot)': ['保护下自由倒立', 'Bǎohù xià zìyóu dàolì'], 'Kick Up Practice': ['踢腿上倒立练习', 'Tī tuǐ shàng dàolì liànxí'],
  'Full Handstand': ['完全手倒立', 'Wánquán shǒu dàolì'],
};

export const cnFor = (name: string): [string, string] | null =>
  MANDARIN[CANON(name)] || MANDARIN[name] || null;
